language: python
python:
  - "3.6"
  - "pypy3.6"

# Install dependencies
install:
  - pip install pylint
  - pip install -r requirements.txt

# Run Tests
script:
  - pylint --output-format=text __init__.py
